/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminMonthlyReportRouteImport } from './routes/admin/monthly-report'
import { Route as AdminAddUserIndexRouteImport } from './routes/admin/add-user/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMonthlyReportRoute = AdminMonthlyReportRouteImport.update({
  id: '/admin/monthly-report',
  path: '/admin/monthly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAddUserIndexRoute = AdminAddUserIndexRouteImport.update({
  id: '/admin/add-user/',
  path: '/admin/add-user/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/monthly-report': typeof AdminMonthlyReportRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/add-user/': typeof AdminAddUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/monthly-report': typeof AdminMonthlyReportRoute
  '/admin': typeof AdminIndexRoute
  '/admin/add-user': typeof AdminAddUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/monthly-report': typeof AdminMonthlyReportRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/add-user/': typeof AdminAddUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/monthly-report' | '/admin/' | '/admin/add-user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/monthly-report' | '/admin' | '/admin/add-user'
  id:
    | '__root__'
    | '/'
    | '/admin/monthly-report'
    | '/admin/'
    | '/admin/add-user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminMonthlyReportRoute: typeof AdminMonthlyReportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAddUserIndexRoute: typeof AdminAddUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monthly-report': {
      id: '/admin/monthly-report'
      path: '/admin/monthly-report'
      fullPath: '/admin/monthly-report'
      preLoaderRoute: typeof AdminMonthlyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/add-user/': {
      id: '/admin/add-user/'
      path: '/admin/add-user'
      fullPath: '/admin/add-user/'
      preLoaderRoute: typeof AdminAddUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminMonthlyReportRoute: AdminMonthlyReportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAddUserIndexRoute: AdminAddUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
